# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Tell you what branch you are watching
trigger:
- master

# Tells you what type of vmImage you will be using
pool:
  vmImage: 'ubuntu-latest'

# The sequential steps to follow to build, run, test, deploy, etc... your app
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
